Issue#17 develop token manager
jaewgwon/wtfru pull request #27
Opened 2021-08-01 11:15 UTC by psymoney

close #17 
JWT 토큰 , Spring security 환경을 구축하고 POST Session 요청 시 JWT 토큰을 Bearer로 반환하도록 구현하였습니다.
추가적으로 프로젝트 파일 구조를 변경하였습니다.

2021-08-09 08:35 UTC, Kim-S-Min reviewed
Comment 확인 부탁드립니다

2021-08-09 11:46 UTC, psymoney commented on backend/src/main/java/com/wtfru/backend/jwt/JwtFilter.java
> +public class JwtFilter extends GenericFilter {
확인하여 반영하였습니다.

2021-08-10 11:50 UTC, Kim-S-Min reviewed
LGTM

2021-08-11 13:17 UTC, jaewgwon requested changes
리뷰 대응 완료시 resolve및 멘션 부탁합니다.

2021-08-11 13:17 UTC, jaewgwon commented on backend/src/main/java/com/wtfru/backend/service/SessionServiceImpl.java
> +            throw new UsernameNotFoundException(sessionTitle + " -> 데이터베이스에서 찾을 수 없습니다.");
## ask

(이하 해당 클래스의 throw 처리한 예외들 모두)
controller layer에서 에러 처리할 예정인가요?  

## nits

SessionDTO가 null인 상황에서, UsernameotFoundException을 throw하는 것 보다는,  
DataNotFoundException정도가 맞지 않을지.. (이외의 익셉션도 전부 한번 검토 바랍니다!)

2021-08-11 13:17 UTC, jaewgwon commented on backend/src/main/java/com/wtfru/backend/service/TokenService.java
> +                .authenticate(new UsernamePasswordAuthenticationToken(request.get("title"), request.get("password")));
## nits

String "title"과 "password"는 constant value로 따로 관리하는게 좋을 듯.  
(위쪽에 map에서 get() 사용하는 패턴 전부 동일)

2021-08-11 13:17 UTC, jaewgwon commented on backend/src/main/java/com/wtfru/backend/service/TokenService.java
> +        this.tokenValidityInMilliseconds = tokenValidityInSeconds * 1000;
## ask

모든 처리가 ms로 이루어질 예정이라면, 처음부터 키를 second단위로 관리하는 이유가 무엇인가요?

2021-08-12 01:42 UTC, psymoney commented on backend/src/main/java/com/wtfru/backend/service/TokenService.java
> +        this.tokenValidityInMilliseconds = tokenValidityInSeconds * 1000;
### answer
Data의 매개변수로 ms가 사용되기 때문에 최종 처리는 ms로 활용하였으나,
키를 second 단위로 관리한 이유는 ms단위로 token validity를 설정할 필요가 없으며 초 단위가 ms보다 익숙하고 직관적이기에 이와 같이 설정하였습니다.

2021-08-12 03:52 UTC, psymoney commented on backend/src/main/java/com/wtfru/backend/service/SessionServiceImpl.java
> +            throw new UsernameNotFoundException(sessionTitle + " -> 데이터베이스에서 찾을 수 없습니다.");
## answer
`UsernameNotFoundException`은 비즈니스 로직에서 호출되지 않으며, 
Spring Security 커스터마이징 인터페이스 구현을 위해 `UserDetailService`를 상속 받은 `loadUserByUsername` 메서드를 override 하는 과정에서 추가하였습니다. 
해당 메서드가 throw하는 익셉션이 `UsernameNotFoundException`이라 동일한 익셉션 쓰로잉 하도록 작성하였습니다.
이외의 익셉션은 기존 `SessionService` 및 `Controller` branch에서 작성한 내용과 동일하며, file structure 재구성 하는 과정에서 modified 된 것으로 반영되어 커밋에 같이 올라오게 되었습니다.

2021-08-12 03:53 UTC, psymoney commented on backend/src/main/java/com/wtfru/backend/service/TokenService.java
> +                .authenticate(new UsernamePasswordAuthenticationToken(request.get("title"), request.get("password")));
@jaewgwon 다른 comments 확인 완료하였고 관련 문의내역 검토 요청드립니다.

2021-08-13 11:39 UTC, Kim-S-Min reviewed
LGTM

2021-08-13 11:48 UTC, jaewgwon commented on backend/src/main/java/com/wtfru/backend/service/TokenService.java
> +                .authenticate(new UsernamePasswordAuthenticationToken(request.get("title"), request.get("password")));
@psymoney 
DTO가 훨씬 나을듯!

2021-08-14 13:03 UTC, psymoney commented
@jaewgwon 
function attribute 수정 및 merging conflicts 해결하였습니다.

2021-08-16 07:53 UTC, jaewgwon approved these changes

2021-08-16 07:53 UTC, merged